
//Authentication
export const USER_AUTHENTICATION = "USER_AUTHENTICATION";
export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED";